pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet build
  displayName: 'Build code generator'
  workingDirectory: AzurePipelineTasks

- script: dotnet run -- ../AzurePipelineAsCode.NET
  displayName: 'Generate code'
  workingDirectory: AzurePipelineTasks

- script: dotnet build
  displayName: 'Build generated code'
  workingDirectory: AzurePipelineAsCode.NET

- script: dotnet run -- "../AzurePipelineAsCode.NET" "$(nugetVersionStorage)"
  displayName: 'Create nuget with updated version number, if required'
  workingDirectory: UpdateVersionNumber


- task: PublishBuildArtifacts@1
  displayName: 'Publish nuget as artifact'
  inputs:
    PathtoPublish: AzurePipelineAsCode.NET/bin/Release
    ArtifactName: AzurePipelineAsCode.NET
