pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: dotnet build
  displayName: 'Build code generator'
  workingDirectory: AzurePipelineTasks

- script: dotnet run -- ../AzurePipelineAsCode.NET
  displayName: 'Generate code'
  workingDirectory: AzurePipelineTasks

- script: dotnet build
  displayName: 'Build generated code'
  workingDirectory: AzurePipelineAsCode.NET

- script: dotnet pack AzurePipelineAsCode.NET\AzurePipelineAsCode.NET.csproj -c Release
  displayName: 'Create nuget package'

- task: PublishBuildArtifacts@1
  displayName: 'Publish nuget as artifact'
  inputs:
    PathtoPublish: AzurePipelineAsCode.NET/bin/Release
    ArtifactName: AzurePipelineAsCode.NET
